name: Sync Backend to QA Repository

on:
  push:
    branches:
      - qa-repo  # Trigger this workflow when changes are pushed to the `main` branch

jobs:
  sync-to-qa:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the backend repository (assuming this is set up in the frontend repository's workflow)
      - name: Checkout Backend Repository
        uses: actions/checkout@v3
        with:
          repository: AmaliTech-Training-Academy/skillspace-backend  # Replace with your frontend repository name
          ref: dev  # Use the branch you want to pull changes from
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Clone the QA repository
      - name: Clone QA Repository
        env:
          QA_REPO_PAT: ${{ secrets.QA_REPO_PAT }}  # Use your Personal Access Token secret
        run: |
          git clone https://${{ secrets.QA_REPO_PAT }}@github.com/AmaliTech-Training-Academy/skillspace-qa.git skillspace-backend 
          cd skillspace-backend

      # Step 3: Create or clean the skillspace-backend folder inside the QA repository
      - name: Prepare `skillspace-backend` Folder in QA Repository
        run: |
          rm -rf skillspace-backend/*
          mkdir -p skillspace-backend
          

      # Step 4: Copy frontend code into the `skillspace-backend` folder of the QA repository
      - name: Copy Frontend to skillspace-backend Folder
        run: |
          rsync -av --exclude='.git' ./ skillspace-backend/

      # Step 5: Commit and push the changes to the QA repository
      - name: Commit and Push Changes to QA
        working-directory: skillspace-backend
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync frontend changes to skillspace-backend folder"
          git push origin main 
